import Head from 'next/head'
import Link from 'next/link'
import { getProductsByCategory, getAllCategoriesAndSubCategories } from "@/utils/getProductsByCategory"

export default function Home({ products, categories }) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ "display": "grid", "placeItems": "center" }}>
        <h1>Productos</h1>
        <div>
          {
            products.map(product => {
              return (
                <Link key={product.nombre} href={`/producto/${product.idproducto}`}>
                  <p>{product.nombre}</p>
                </Link>
              )
            })
          }
        </div>
        <h3>Categorias</h3>
        <div>
          {
            categories.map(category => <p key={category.parent.nombre}>{category.parent.nombre}</p>)
          }
        </div>
      </div>
    </>
  )
}

export async function getStaticProps() {

  // cat. 129 DESTACADOS
  // cat. 0 TODOS LOS PRODUCTOS
  const products = await getProductsByCategory(129)
  const categories = await getAllCategoriesAndSubCategories()

  return {
    props: {
      products: products[0],
      categories: categories,
    },
    revalidate: 10,
  }
}